// <auto-generated />
using Gradeflex.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gradeflex.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230118173959_ProfessorDataSeeding")]
    partial class ProfessorDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gradeflex.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.CourseStudent", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CoursesStudents");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Afm")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Afm = 194394052,
                            Department = "Economics",
                            Name = "Jannie",
                            Surname = "Waelchi",
                            UserId = 51
                        },
                        new
                        {
                            Id = 2,
                            Afm = 116321252,
                            Department = "Informatics",
                            Name = "Keven",
                            Surname = "Boehm",
                            UserId = 52
                        },
                        new
                        {
                            Id = 3,
                            Afm = 128665219,
                            Department = "Economics",
                            Name = "Glen",
                            Surname = "Kassulke",
                            UserId = 53
                        },
                        new
                        {
                            Id = 4,
                            Afm = 335517960,
                            Department = "Informatics",
                            Name = "Keira",
                            Surname = "Larson",
                            UserId = 54
                        },
                        new
                        {
                            Id = 5,
                            Afm = 173082468,
                            Department = "Economics",
                            Name = "Fannie",
                            Surname = "Gerlach",
                            UserId = 55
                        },
                        new
                        {
                            Id = 6,
                            Afm = 348727676,
                            Department = "Economics",
                            Name = "Patricia",
                            Surname = "Rutherford",
                            UserId = 56
                        },
                        new
                        {
                            Id = 7,
                            Afm = 373554057,
                            Department = "Economics",
                            Name = "Jaycee",
                            Surname = "Homenick",
                            UserId = 57
                        },
                        new
                        {
                            Id = 8,
                            Afm = 113797021,
                            Department = "Economics",
                            Name = "Tamara",
                            Surname = "Waelchi",
                            UserId = 58
                        },
                        new
                        {
                            Id = 9,
                            Afm = 423397640,
                            Department = "Informatics",
                            Name = "Josiane",
                            Surname = "Kris",
                            UserId = 59
                        },
                        new
                        {
                            Id = 10,
                            Afm = 490437810,
                            Department = "Informatics",
                            Name = "Vicente",
                            Surname = "Lueilwitz",
                            UserId = 60
                        });
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Secretary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Secretaries");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Economics",
                            Name = "Crystel",
                            RegistrationNumber = 1900,
                            Surname = "Keeling",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "Informatics",
                            Name = "Darien",
                            RegistrationNumber = 1900,
                            Surname = "Roberts",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Department = "Informatics",
                            Name = "Antonietta",
                            RegistrationNumber = 1901,
                            Surname = "Windler",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Department = "Economics",
                            Name = "Esperanza",
                            RegistrationNumber = 1901,
                            Surname = "Bechtelar",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Department = "Informatics",
                            Name = "Anastasia",
                            RegistrationNumber = 1902,
                            Surname = "Bechtelar",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Department = "Economics",
                            Name = "Armand",
                            RegistrationNumber = 1902,
                            Surname = "Connelly",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Department = "Economics",
                            Name = "Lorenzo",
                            RegistrationNumber = 1903,
                            Surname = "Hegmann",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Department = "Economics",
                            Name = "Ali",
                            RegistrationNumber = 1904,
                            Surname = "Bergstrom",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Department = "Informatics",
                            Name = "Connie",
                            RegistrationNumber = 1903,
                            Surname = "Wilkinson",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Department = "Economics",
                            Name = "Leola",
                            RegistrationNumber = 1905,
                            Surname = "Nienow",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Department = "Economics",
                            Name = "Monique",
                            RegistrationNumber = 1906,
                            Surname = "Schultz",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Department = "Informatics",
                            Name = "Maeve",
                            RegistrationNumber = 1904,
                            Surname = "Hauck",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Department = "Informatics",
                            Name = "Philip",
                            RegistrationNumber = 1905,
                            Surname = "Sporer",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Department = "Economics",
                            Name = "Roderick",
                            RegistrationNumber = 1907,
                            Surname = "Jaskolski",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Department = "Economics",
                            Name = "Oral",
                            RegistrationNumber = 1908,
                            Surname = "Runolfsson",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Department = "Economics",
                            Name = "Rashawn",
                            RegistrationNumber = 1909,
                            Surname = "Johns",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Department = "Informatics",
                            Name = "Jayme",
                            RegistrationNumber = 1906,
                            Surname = "Johnston",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Department = "Informatics",
                            Name = "Jacquelyn",
                            RegistrationNumber = 1907,
                            Surname = "Adams",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Department = "Informatics",
                            Name = "Sherwood",
                            RegistrationNumber = 1908,
                            Surname = "Daugherty",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Department = "Informatics",
                            Name = "Sanford",
                            RegistrationNumber = 1909,
                            Surname = "Balistreri",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Department = "Economics",
                            Name = "Lucy",
                            RegistrationNumber = 1910,
                            Surname = "Kohler",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            Department = "Informatics",
                            Name = "Nils",
                            RegistrationNumber = 1910,
                            Surname = "Mitchell",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            Department = "Informatics",
                            Name = "Rylan",
                            RegistrationNumber = 1911,
                            Surname = "Jacobi",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            Department = "Economics",
                            Name = "Marco",
                            RegistrationNumber = 1911,
                            Surname = "Graham",
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            Department = "Informatics",
                            Name = "Alivia",
                            RegistrationNumber = 1912,
                            Surname = "Schmeler",
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            Department = "Economics",
                            Name = "Adell",
                            RegistrationNumber = 1912,
                            Surname = "Gibson",
                            UserId = 26
                        },
                        new
                        {
                            Id = 27,
                            Department = "Informatics",
                            Name = "Gordon",
                            RegistrationNumber = 1913,
                            Surname = "Hudson",
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            Department = "Economics",
                            Name = "Brendon",
                            RegistrationNumber = 1913,
                            Surname = "Cassin",
                            UserId = 28
                        },
                        new
                        {
                            Id = 29,
                            Department = "Informatics",
                            Name = "Jon",
                            RegistrationNumber = 1914,
                            Surname = "Goldner",
                            UserId = 29
                        },
                        new
                        {
                            Id = 30,
                            Department = "Economics",
                            Name = "Travis",
                            RegistrationNumber = 1914,
                            Surname = "Russel",
                            UserId = 30
                        },
                        new
                        {
                            Id = 31,
                            Department = "Informatics",
                            Name = "Orlo",
                            RegistrationNumber = 1915,
                            Surname = "Ward",
                            UserId = 31
                        },
                        new
                        {
                            Id = 32,
                            Department = "Economics",
                            Name = "Rahsaan",
                            RegistrationNumber = 1915,
                            Surname = "Dietrich",
                            UserId = 32
                        },
                        new
                        {
                            Id = 33,
                            Department = "Economics",
                            Name = "Keaton",
                            RegistrationNumber = 1916,
                            Surname = "Auer",
                            UserId = 33
                        },
                        new
                        {
                            Id = 34,
                            Department = "Informatics",
                            Name = "Mina",
                            RegistrationNumber = 1916,
                            Surname = "Will",
                            UserId = 34
                        },
                        new
                        {
                            Id = 35,
                            Department = "Informatics",
                            Name = "Mitchell",
                            RegistrationNumber = 1917,
                            Surname = "Schulist",
                            UserId = 35
                        },
                        new
                        {
                            Id = 36,
                            Department = "Informatics",
                            Name = "Arielle",
                            RegistrationNumber = 1918,
                            Surname = "Johnson",
                            UserId = 36
                        },
                        new
                        {
                            Id = 37,
                            Department = "Informatics",
                            Name = "Jeffery",
                            RegistrationNumber = 1919,
                            Surname = "Terry",
                            UserId = 37
                        },
                        new
                        {
                            Id = 38,
                            Department = "Economics",
                            Name = "Anita",
                            RegistrationNumber = 1917,
                            Surname = "Kozey",
                            UserId = 38
                        },
                        new
                        {
                            Id = 39,
                            Department = "Economics",
                            Name = "Delphine",
                            RegistrationNumber = 1918,
                            Surname = "Langosh",
                            UserId = 39
                        },
                        new
                        {
                            Id = 40,
                            Department = "Informatics",
                            Name = "Bernadette",
                            RegistrationNumber = 1920,
                            Surname = "Franecki",
                            UserId = 40
                        },
                        new
                        {
                            Id = 41,
                            Department = "Informatics",
                            Name = "Hilbert",
                            RegistrationNumber = 1921,
                            Surname = "Walsh",
                            UserId = 41
                        },
                        new
                        {
                            Id = 42,
                            Department = "Economics",
                            Name = "Keara",
                            RegistrationNumber = 1919,
                            Surname = "Toy",
                            UserId = 42
                        },
                        new
                        {
                            Id = 43,
                            Department = "Informatics",
                            Name = "Jarrett",
                            RegistrationNumber = 1922,
                            Surname = "Feeney",
                            UserId = 43
                        },
                        new
                        {
                            Id = 44,
                            Department = "Economics",
                            Name = "Zakary",
                            RegistrationNumber = 1920,
                            Surname = "Klein",
                            UserId = 44
                        },
                        new
                        {
                            Id = 45,
                            Department = "Informatics",
                            Name = "Bridie",
                            RegistrationNumber = 1923,
                            Surname = "Padberg",
                            UserId = 45
                        },
                        new
                        {
                            Id = 46,
                            Department = "Informatics",
                            Name = "Judah",
                            RegistrationNumber = 1924,
                            Surname = "Jast",
                            UserId = 46
                        },
                        new
                        {
                            Id = 47,
                            Department = "Informatics",
                            Name = "Arnoldo",
                            RegistrationNumber = 1925,
                            Surname = "Kerluke",
                            UserId = 47
                        },
                        new
                        {
                            Id = 48,
                            Department = "Economics",
                            Name = "Laverne",
                            RegistrationNumber = 1921,
                            Surname = "King",
                            UserId = 48
                        },
                        new
                        {
                            Id = 49,
                            Department = "Economics",
                            Name = "Dawn",
                            RegistrationNumber = 1922,
                            Surname = "Ratke",
                            UserId = 49
                        },
                        new
                        {
                            Id = 50,
                            Department = "Informatics",
                            Name = "Chelsie",
                            RegistrationNumber = 1926,
                            Surname = "Macejkovic",
                            UserId = 50
                        });
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "qhE1stPv7e",
                            Role = "student",
                            Username = "Esta27"
                        },
                        new
                        {
                            Id = 2,
                            Password = "UzuQW7cnng",
                            Role = "student",
                            Username = "Berneice.Anderson3"
                        },
                        new
                        {
                            Id = 3,
                            Password = "qWoyQVd2wC",
                            Role = "student",
                            Username = "Clint79"
                        },
                        new
                        {
                            Id = 4,
                            Password = "lf9PUBSlx7",
                            Role = "student",
                            Username = "Darion37"
                        },
                        new
                        {
                            Id = 5,
                            Password = "RYDgJrk_NQ",
                            Role = "student",
                            Username = "Holly.Schmeler"
                        },
                        new
                        {
                            Id = 6,
                            Password = "oqXLHhvwuV",
                            Role = "student",
                            Username = "Cristobal_Schaefer87"
                        },
                        new
                        {
                            Id = 7,
                            Password = "6EKTusVJyC",
                            Role = "student",
                            Username = "Leif_Tremblay42"
                        },
                        new
                        {
                            Id = 8,
                            Password = "ElgWEvxUSL",
                            Role = "student",
                            Username = "Lavinia48"
                        },
                        new
                        {
                            Id = 9,
                            Password = "Gk_tWSFcvZ",
                            Role = "student",
                            Username = "Savanah.Bayer"
                        },
                        new
                        {
                            Id = 10,
                            Password = "0diQDeLHJO",
                            Role = "student",
                            Username = "Hugh.Kerluke29"
                        },
                        new
                        {
                            Id = 11,
                            Password = "Ii3gZvjQew",
                            Role = "student",
                            Username = "Kacey.Wolff"
                        },
                        new
                        {
                            Id = 12,
                            Password = "k6ttm6r3ZD",
                            Role = "student",
                            Username = "Alene42"
                        },
                        new
                        {
                            Id = 13,
                            Password = "yHrberJefI",
                            Role = "student",
                            Username = "Lawrence97"
                        },
                        new
                        {
                            Id = 14,
                            Password = "DWfz0LIMjm",
                            Role = "student",
                            Username = "Bobby.Daugherty"
                        },
                        new
                        {
                            Id = 15,
                            Password = "jmdsmszM2p",
                            Role = "student",
                            Username = "Weston33"
                        },
                        new
                        {
                            Id = 16,
                            Password = "YTEmjTmXzx",
                            Role = "student",
                            Username = "Kayley.Wuckert91"
                        },
                        new
                        {
                            Id = 17,
                            Password = "UxqrEpLlMw",
                            Role = "student",
                            Username = "Jamar.Bosco33"
                        },
                        new
                        {
                            Id = 18,
                            Password = "WjDySwDMD2",
                            Role = "student",
                            Username = "Presley.Wiza"
                        },
                        new
                        {
                            Id = 19,
                            Password = "Oi778g_zpG",
                            Role = "student",
                            Username = "Lavonne.Lang97"
                        },
                        new
                        {
                            Id = 20,
                            Password = "wSGDhvK93x",
                            Role = "student",
                            Username = "Delphine_Wilderman"
                        },
                        new
                        {
                            Id = 21,
                            Password = "xRvZU_rhIF",
                            Role = "student",
                            Username = "Nigel33"
                        },
                        new
                        {
                            Id = 22,
                            Password = "Ez5rNAPSBf",
                            Role = "student",
                            Username = "Pansy_Heller"
                        },
                        new
                        {
                            Id = 23,
                            Password = "dmOLTZMqGA",
                            Role = "student",
                            Username = "Gracie_Will47"
                        },
                        new
                        {
                            Id = 24,
                            Password = "cTlUCMuiff",
                            Role = "student",
                            Username = "Florine69"
                        },
                        new
                        {
                            Id = 25,
                            Password = "KVazEVyiyQ",
                            Role = "student",
                            Username = "Weldon.Dare16"
                        },
                        new
                        {
                            Id = 26,
                            Password = "6pD05_821P",
                            Role = "student",
                            Username = "Nathanial42"
                        },
                        new
                        {
                            Id = 27,
                            Password = "AeLnRVVT70",
                            Role = "student",
                            Username = "Alfonso.Jacobson"
                        },
                        new
                        {
                            Id = 28,
                            Password = "gmDIeJgnav",
                            Role = "student",
                            Username = "Greyson13"
                        },
                        new
                        {
                            Id = 29,
                            Password = "e20PkD0l0W",
                            Role = "student",
                            Username = "Georgette_Bergnaum"
                        },
                        new
                        {
                            Id = 30,
                            Password = "xElwubD7D0",
                            Role = "student",
                            Username = "Rylan_Berge"
                        },
                        new
                        {
                            Id = 31,
                            Password = "hn1Z4wy9P0",
                            Role = "student",
                            Username = "Kathryne_Brown71"
                        },
                        new
                        {
                            Id = 32,
                            Password = "eod2FAzj69",
                            Role = "student",
                            Username = "Olaf32"
                        },
                        new
                        {
                            Id = 33,
                            Password = "sVVdLqEEZG",
                            Role = "student",
                            Username = "Darrick_Dibbert"
                        },
                        new
                        {
                            Id = 34,
                            Password = "x__HXc9KRA",
                            Role = "student",
                            Username = "Jade48"
                        },
                        new
                        {
                            Id = 35,
                            Password = "cFXlzs0wjN",
                            Role = "student",
                            Username = "Mustafa_Towne"
                        },
                        new
                        {
                            Id = 36,
                            Password = "tyuBr_Yqds",
                            Role = "student",
                            Username = "Alexis_Price92"
                        },
                        new
                        {
                            Id = 37,
                            Password = "z1cj8wP6he",
                            Role = "student",
                            Username = "Judson49"
                        },
                        new
                        {
                            Id = 38,
                            Password = "peoEfEpKSZ",
                            Role = "student",
                            Username = "Jamar58"
                        },
                        new
                        {
                            Id = 39,
                            Password = "2V25sp8QA0",
                            Role = "student",
                            Username = "Neva_Watsica64"
                        },
                        new
                        {
                            Id = 40,
                            Password = "PTZbRwyhRY",
                            Role = "student",
                            Username = "Burnice12"
                        },
                        new
                        {
                            Id = 41,
                            Password = "4rOEHm52Vz",
                            Role = "student",
                            Username = "Darren_Schmidt90"
                        },
                        new
                        {
                            Id = 42,
                            Password = "1be4GQCrkP",
                            Role = "student",
                            Username = "Anahi10"
                        },
                        new
                        {
                            Id = 43,
                            Password = "dhGWiMTdao",
                            Role = "student",
                            Username = "Hazle_Quigley"
                        },
                        new
                        {
                            Id = 44,
                            Password = "KZ2m0hjmMI",
                            Role = "student",
                            Username = "Art62"
                        },
                        new
                        {
                            Id = 45,
                            Password = "Us5XKVIUo0",
                            Role = "student",
                            Username = "Tiara49"
                        },
                        new
                        {
                            Id = 46,
                            Password = "nTbhNawGsF",
                            Role = "student",
                            Username = "Amara46"
                        },
                        new
                        {
                            Id = 47,
                            Password = "je5YTPKzK7",
                            Role = "student",
                            Username = "Carmela.McDermott89"
                        },
                        new
                        {
                            Id = 48,
                            Password = "XeXR_XWL0P",
                            Role = "student",
                            Username = "Joseph.Huel68"
                        },
                        new
                        {
                            Id = 49,
                            Password = "4anfKB6HuE",
                            Role = "student",
                            Username = "Fleta.Kutch"
                        },
                        new
                        {
                            Id = 50,
                            Password = "TVMpGLNOPi",
                            Role = "student",
                            Username = "Reinhold44"
                        },
                        new
                        {
                            Id = 51,
                            Password = "nDwjY1YOHx",
                            Role = "professor",
                            Username = "Markus_Moen"
                        },
                        new
                        {
                            Id = 52,
                            Password = "mMnMe0u_wD",
                            Role = "professor",
                            Username = "Peter.Doyle2"
                        },
                        new
                        {
                            Id = 53,
                            Password = "F7En_zLUjo",
                            Role = "professor",
                            Username = "Abbey38"
                        },
                        new
                        {
                            Id = 54,
                            Password = "AKTpfsPaH3",
                            Role = "professor",
                            Username = "Kristina_McClure"
                        },
                        new
                        {
                            Id = 55,
                            Password = "dmoQ9gE6ol",
                            Role = "professor",
                            Username = "Lillie_Jenkins85"
                        },
                        new
                        {
                            Id = 56,
                            Password = "MEHQpB707d",
                            Role = "professor",
                            Username = "King_Langworth84"
                        },
                        new
                        {
                            Id = 57,
                            Password = "EAApa_NzLK",
                            Role = "professor",
                            Username = "Tyson_Prosacco62"
                        },
                        new
                        {
                            Id = 58,
                            Password = "5XZqrRGmiS",
                            Role = "professor",
                            Username = "Maida.Lesch39"
                        },
                        new
                        {
                            Id = 59,
                            Password = "_Oh48FQs0b",
                            Role = "professor",
                            Username = "Jarod.Wilkinson"
                        },
                        new
                        {
                            Id = 60,
                            Password = "I72aQw1Wde",
                            Role = "professor",
                            Username = "Brad.OKeefe73"
                        });
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Course", b =>
                {
                    b.HasOne("Gradeflex.Data.Entities.Professor", "Professor")
                        .WithMany("Courses")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.CourseStudent", b =>
                {
                    b.HasOne("Gradeflex.Data.Entities.Course", "Course")
                        .WithMany("CoursesStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gradeflex.Data.Entities.Student", "Student")
                        .WithMany("CoursesStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Grade", b =>
                {
                    b.HasOne("Gradeflex.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gradeflex.Data.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Professor", b =>
                {
                    b.HasOne("Gradeflex.Data.Entities.User", "User")
                        .WithOne("Professor")
                        .HasForeignKey("Gradeflex.Data.Entities.Professor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Secretary", b =>
                {
                    b.HasOne("Gradeflex.Data.Entities.User", "User")
                        .WithOne("Secretary")
                        .HasForeignKey("Gradeflex.Data.Entities.Secretary", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Student", b =>
                {
                    b.HasOne("Gradeflex.Data.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Gradeflex.Data.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Course", b =>
                {
                    b.Navigation("CoursesStudents");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Professor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.Student", b =>
                {
                    b.Navigation("CoursesStudents");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Gradeflex.Data.Entities.User", b =>
                {
                    b.Navigation("Professor");

                    b.Navigation("Secretary");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
